### ISSUE TITLE
Use more "filler" markup elements like <div>

### ISSUE THREAD

**Issue by Aquaticat** [Aquaticat/2023apr06.legacy.monochromatic.dev#2]
So, when I first designed this, I thought it might be the best if I used as few non-semantic tags as possible.

But that clearly isn't working in my favor. There are many things that can easily be done using flexbox, but because of my stubbornness of not adding a `<div>` tag, I had to use CSS grid to do the same thing, which is magnitudes more complex.

Using manual breakpoints might be a good idea, but I just thought that is "inelegant". But where is elegance if I can't get stuff done in the first place?

Not to mention the overuse of `::before` and `::after` pseudo elements to fulfill a functionality that could be better fulfilled by a simple `span`.

See, I thought it might be the best if I offload as much work as possible for writing HTML. But that certainly can take a backseat. I think having author writing a `<div>` occasionally is not that bad.

Therefore, I will use more filler markup elements from now on.

Like:

```html
<details id='Do_not_Be_Stubborn'>
<summary>
  <h1>
    Do not Be Stubborn
  </h1>
</summary>
<!-- I don't really need the class here.
     But this way I know for sure it's the content wrapper and
     not just some random div element that someone happens to use incorrectly. -->
<div class='details__contentWrapper'>
<p>Really.</p>

<p>Just don&quot;t</p>
</div>
</details>
```

So I can write

```CSS
/* I don't really need to specify the div tag here, but I just want to.
   Sometimes doing this makes me have a bit more clue when writing CSS.
   Because this way I know for sure it's a div element and not something else at first glance. */
details > div.details__contentWrapper {
  margin-inline: 1em;
}
```

instead of

```CSS
details > * {
  /* Might override margin-inline that is needed by some content elements.
     Bad. */
  margin-inline: 1em;
}

details > summary {
  margin-inline: unset;
}
```
